require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Include:
    - app/**/*.rb
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Rails

Rails/DynamicFindBy:
  Enabled: false

Rails/Output:
  Exclude: 
    - app/core/interface/**/*.rb

Rails/Exit:
  Exclude:
    - app/core/interface/**/*.rb

Rails/TimeZone:
  Enabled: false

# RSpec

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false